### ISSUE TITLE
Make installation independent of `poetry`

### ISSUE THREAD

**Issue by sindre-nistad** [equinor/omnia-timeseries-python#63]
**Is your feature request related to a problem? Please describe.**
When `omnia-timeseries-python` is included in a project, `poetry` is also installed because it is mentioned in `pyproject.toml`.

In a separate project I've been asked to look through, there was an issue where `snyk` would detect a vulnerability in `virualenv`, which is used by `poetry`.
It seems that hard dependency is unnecessary.

**Describe the solution you'd like**

I'd like `pyproject.toml` to be compliant with a [standard build specification](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/).

Specifically, the `pyproject.toml` could be rewritten as 

```toml
[project]
name = "omnia_timeseries"
version = "1.3.12"
authors = [
    { name = "Equinor Omnia Industrial IoT Team", email = "omniaindiot@equinor.com" },
]
description = "Official Python SDK for the Omnia Timeseries API"
readme = "README.md"

requires-python = ">=3.8,<4.0"
dependencies = [
    "requests",
    "azure-identity>=1.19.0",
    "azure-core",
    "opentelemetry-instrumentation-requests>=0.48b0",
    "opentelemetry-api>=1.27.0",
    "cryptography>=43.0.1",
    "pyjwt>=2.9.0",
]

[project.optional-dependencies]
test = [
    "pytest",
    "requests-mock",
]

[project.urls]
homepage = "https://github.com/equinor/omnia-timeseries-python"
repository = "https://github.com/equinor/omnia-timeseries-python"

[build-system]
requires = ["setuptools>=64.0"]
build-backend = "setuptools.build_meta"

```

This would likely require minor adjustments to be `.github/workflows/deploy.yml`.

**Describe alternatives you've considered**
In our case, we could simply update `poetry` / `virtualenv`, but I though it prudent to let you know of an alternative.

**Additional context**
As a bonus, doing this you reduce the installation time for users and reduce the amount of necessary packages that must be downloaded when using `omnia-timeseries-python`
